words = [
    "Wiązać koniec z końcem",
"Kto nie ma w głowie, ten ma w nogach",
"Żenic się dla pieniędzy",
"Rozgłośnia radiowa",
"Czyste sumienie",
"Gdy kota nie ma, myszy harcują",
"Baba z wozu - koniom lżej",
"Jajko mądrzejsze od kury",
"Mały deszcz z dużej chmury",
"Tonąć w długach",
"Proste jak bułka z masłem",
"Pogoda pod psem",
"Najciemniej jest pod latarnią",
"Hulaj dusza – piekła nie ma",
"Schody do piekła",
"Jednego słońca dość na niebie",
"Dzień świra",
"Robić się na bóstwo",
"Wstrzymać się od głosu",
"Komu w drogę, temu czas",
"Dobra żona – mężowi korona",
"Dobry żart tynfa wart",
"Prawda w oczy kole",
"Czarny rynek",
"Upadek moralny",
"Pozaziemska cywilizacja",
"Jajko mądrzejsze od kury",
"Stary człowiek i morze",
"Termos z ciepłą herbatą",
"Głową muru nie przebijesz",
"Robić wodę z mózgu",
"Bez pracy trudno dostąpić honoru",
"Łączyć przyjemne z pożytecznym",
"Metoda kija i marchewki",
"Gdzie jedna kość, a dwa brytany – tam pokój nie znany",
"Jeśli wejdziesz między wrony, musisz krakać jak i one",
"Co z oczu, to z serca",
"Zakaz gry w piłke",
"Gdy włos siwieje, rozum dojrzeje",
"Milczenie owiec",
"Od czubka głowy do pięt",
"Chleb i woda, nie ma głoda",
"Czepiać się jak pijany stołu",
"Żółte papiery",
"Nie zostawić na kimś suchej nitki",
"Bez pracy nie ma płacy",
"Każdy kij ma dwa końce",
"Szczęśliwa liczba",
"Koniec świata",
"Bez ludzi i raj się znudzi",
"Przyszła koza do woza",
"Bogatemu diabeł dzieci kołysze",
"Głodny głodnemu wypomni",
"Statek piracki",
"Odsunąć kogoś na dalszy plan",
"Licho nie śpi",
"Wsadzać nos w nie swoje sprawy",
"Bez zachodu nie ma miodu",
"Dzisiaj bal, jutro żal",
"Bez pracy nie ma kołaczy",
"Lustro weneckie",
"Kto się lubi, ten się czubi",
"Ranny ptaszek",
"Bogatemu to i byk się ocieli",
"Strzelać ślepakami",
"Nadzieja matką głupich",
"Szewc bez butów chodzi",
"Pies najlepszym przyjacielem człowieka",
"Jeździec bez głowy",
"Naga prawda",
"Jeszcze tego nie było, by jajko kurę uczyło",
"Nie dla psa kiełbasa",
"Wbić nóż w plecy",
"Szósty zmysł",
"Przypowieść biblijna",
"Wyścig szcurów",
"Fortuna często rozumowi przeczy",
"Piąta woda po kisielu",
"Baba swoje, chłop swoje",
"Głupi i głupszy",
"Jaki ojciec, taki syn",
"Dobrymi chęciami jest piekło wybrukowane",
"Jeszcze się taki nie urodził, co by wszystkim dogodził",
"Spędzać komuś sen z powiek",
"Fortuna kołem się toczy",
"Młyn wodny",
"Nie czyń drugiemu, co tobie niemiłe",
"Statki na niebie",
"Stopa procentowa",
"Bez ładu i składu",
"Burza piaskowa",
"Szybowiec",
"Tratwa ratunkowa",
"Dopóty dzban wodę nosi, dopóki mu się ucho nie urwie",
"Nie udawaj Greka",
"Czego nie bierze Chrystus, to fiskus porwie",
"Elektryka prąd nie tyka",
"Pieniądze nie śmierdzą",
"Strajk włoski",
"Złote gody",
"Książe z bajki na białym koniu",
"Beczka prochu",
"Błędne koło",
"Bilet miesięczny",
"Rozdwojenie jaźni",
"I Herkules dupa, kiedy ludzi kupa",
"Raz na wozie, raz pod wozem",
"Czterolistna koniczyna",
"Trzymac kogoś krótko",
"Czego oko nie widzi, tego sercu nie żal",
"Nosił wilk razy kilka, ponieśli i wilka",
"Wyścig slimaków",
"Z deszczu pod rynnę",
"Śmiać się jak głupi do sera",
"Abecadło z pieca spadło",
"Klasowy pajac",
"Gość w dom, Bóg w dom",
"Koń trojański",
"Bitwa morska",
"Oda do miłości",
"Droga ewakuacyjna",
"Archiwum Watykańskie",
"Z dużej chmury mały deszcz",
"Na złodzieju czapka gore",
"Wyszło szydło z worka",
"Niebo w gębie",
"Gwóźdź programu",
"Gdyby babcia miała wąsy, toby była dziadkiem",
"Miłość jest ślepa",
"Elektrownia atomowa",
"Policyjna prowokacja",
"Ćwiczenie czyni mistrza",
"Pędzić na złamanie karku",
"Podróże kształcą",
"Gdy wilk się zestarzeje, skubie go i wrona",
"Kupić coś na kreskę",
"Bieda z dziećmi, bieda i bez dzieci",
"Cudza praca nie wzbogaca",
"Mieć znajomości",
"Było dwóch braci mądrych, a trzeci żonaty",
"Jak amen w pacierzu",
"Lepiej późno niż wcale",
"Jechać na podwójnym gazie",
"Pieniądze szczęścia nie dają",
"Psy szczekają, karawana idzie dalej",
"Drzewo genealogiczne",
"Baba swoje, czart swoje",
"Miód wielokwiatowy",
"Do ojca po grosz, do matki po koszulę",
"Między bogiem a prawdą",
"Co za dużo, to niezdrowo",
"Sadzawka",
"Dziurawe wiadro",
"Do trzech razy sztuka",
"Złota rączka",
"Nie ma tego złego, co by na dobre nie wyszło",
"Cicha woda brzegi rwie",
"Głodnemu chleb na myśli",
"Być w Rzymie i nie widzieć papieża",
"Gaj oliwny",
"Gra w kiery wyrabia maniery",
"Bliźniaki syjamskie",
"Krem do rąk",
"Krowa, która dużo ryczy, mało mleka daje",
"Co Anglik zmyśli, Francuz skréśli, a Niemiec doma nakrupi, wszystko to głupi Polak kupi",
"Bogu się kłaniaj, a diabła nie gniewaj",
"Ksiądz dwa razy kazania nie mówi",
"Nie mieć nic do stracenia",
"Robić z igły widły",
"Kombinuje jak koń pod górę",
"Piąte koło u wozu",
"Indyk myślał o niedzieli, a w sobotę łeb mu ścięli",
"Świat się przewraca do góry nogami",
"Polowanie na czarownice",
"Chrzest bojowy",
"Boga na języku, a diabła ma w sercu",
"Służby porządkowe",
"Błędne koło",
"Łaska pańska na pstrym koniu jeździ",
"Skrzynia skarbów",
"Kto pyta, nie błądzi",
"Refleks szachisty",
"Jak pies je, to nie szczeka",
"Oko za oko, ząb za ząb",
"Okazja czyni złodzieja",
"Gdzie Rzym, gdzie Krym",
"Ryba psuje się od głowy",
"Trafiło się ślepej kurze ziarno",
"Na każdego przyjdzie czas",
"Do wesela się zagoi",
"Tango argentyńskie",
"Mieć dwie lewe ręce",
"Lecieć sobie w kulki",
"Biednemu zawsze wiatr w oczy",
"Śmiać się na cały głos",
"Lot w kosmos",
"Mądrej głowie dość dwie słowie",
"Prawda jak oliwa, zawsze na wierzch wypływa",
"Stół szwedzki",
"Nie pchaj palca między drzwi",
"Kiedy się jaskółka zniża, deszcz się do nas zbliża",
"W zdrowym ciele zdrowy duch",
"Baba o szydle, dziad o mydle",
"Globalne ocieplenie",
"W kwiecie wieku",
"Droga wewnętrzna",
"Umarł król, niech żyje król",
"Małe jest piękne",
"Album ze zdjęciami",
"Każdy as bierze raz",
"Daj kurze grzędę, a ona: wyżej siędę",
"Co mąż, to wąż, co żona, to męczeńska korona",
"Ostatnia Wiecierza",
"Być w swoim żywiole",
"Wiedza to potęga",
"Podpierać powieki zapałkami",
"Niech nie wie lewica, co czyni prawica",
"Co ma wisieć, nie utonie",
"Podpisać pakt z diabłem",
"Zabawa w chowanego",
"Wolna amerykanka",
"Na bezrybiu i rak ryba",
"Ciągnie swój do swego",
"Małpi gaj",
"Policzyć coś na palcach jednej ręki",
"Drzewo bananowe",
"Lepiej dmuchać na zimne",
"Nadzieja umiera ostatnia",
"Palić jak smok",
"Pracować w pocie czoła",
"Lepszy wróbel w garści niż gołąb na dachu",
"Chłop mowny a kot łowny z głodu nie zemrą",
"Modli się pod figurą, a diabła ma za skórą",
"Zaciągać ręczny",
"Jasne jak słońce",
"Człowiek pająk",
"Człowiek człowiekowi wilkiem",
"Czym skorupka za młodu nasiąknie, tym na starość trąci",
"Trakt leśny",
"Kamień węgielny",
"Konkurs rzutów karnych",
"z piasku bicza nie ukręcisz",
"Czuć do kogoś miętę",
"Poranna mgła",
"Najlepsza zasada – patrz w karty sąsiada",
"Jak cię widzą, tak cię piszą",
"Szeptać po kątach",
"Co wolno wojewodzie, to nie tobie, smrodzie",
"Dostrzec coś kątem oka",
"Łowca przygód",
"Narobić sobie wrogów",
"Ślub od pierwszego wejrzenia",
"Nie święci garnki lepią",
"Gry planszowe",
"Kłamać jak z nut",
"Ile wina w głowie, tyle prawdy w słowie",
"Instrument muzyczny",
"Herbata z prądem",
"I wilk syty, i owca cała",
"Czarno na białym",
"Trzecia ręka bije",
"Jedna jaskółka wiosny nie czyni",
"Biedna żona taka, która ma pijaka",
"Wysokie napięcie",
"Kwiat paproci",
"Nie chwal dnia przed zachodem słońca",
"Darowanemu koniowi nie zagląda się w zęby",
"Kolos na glinianych nogach",
"Dzieci i ryby głosu nie mają",
"Nie taki diabeł straszny, jak go malują",
"Przyganiał kocioł garnkowi, a sam smoli",
"Z pustego i Salomon nie naleje",
"Osoba wysoko postawiona",
"Co dwie głowy, to nie jedna",
"Diabeł tkwi w szegółach",
"Nie porywaj się z motyką na słońce",
"Akt wandalizmu",
"Kto mieczem wojuje, od miecza ginie",
"Siedzący tryb życia",
"Obraz nędzy i rozpaczy",
"Szczotka do zębów",
"Apetyt rośnie w miarę jedzenia",
"Sztuczne ognie",
"Kruk krukowi oka nie wykole",
"Schabowy z kapustą",
"Człowiek myśli, Pan Bóg kreśli",
"Kochajmy się jak bracia, liczmy się jak Żydzi",
"Chleb, piwo i świéca zdobią szlachcica",
"Strzelać do własnej bramki",
"Półprawda",
"Kraj kwitnącej wiśni",
"Nie szata zdobi człowieka",
"Jeden z dziesięciu",
"Mądry Polak po szkodzie",
"Przepaść jak kamień w wodę",
"Czuć się jak ryba w wodzie",
"Siódme niebo",
"Jak sobie pościelesz, tak się wyśpisz",
"Syzyfowa praca",
"Diabeł tkwi w szczegółach",
"Kuć żelazo, póki gorące",
"Jak za króla Sasa: jedz, pij i popuszczaj pasa",
"Ciekawość to pierwszy stopień do piekła",
"Strugać durnia",
"Mieć na pieńku",
"Każdy sobie rzepkę skrobie",
"Wino wytrawne",
"Kowal zawinił, a Cygana powiesili",
"Kto nie ma szczęścia w kartach, ten ma szczęście w miłości",
"Cel uświęca środki",
"Nie ma róży bez kolców",
"Lampka nocna",
"Gdzie diabeł nie może, tam babę pośle",
"Kwiat lotosu",
"Pamięć krótkotrwała",
"Jak kamień w wodę",
"Winda do nieba",
"Burza w szklance wody",
"Łódź podwodna",
"Zamek z piasku",
"Szczęśliwi czasu nie liczą",
"Dobra i wdowa, gdy młoda i zdrowa",
"Ogniem i mieczem",
"Habit mnichem nie czyni",
"Ostry cień mgły",
"Kłamstwo ma krótkie nogi",
"Urodzić się pod szczęśliwą gwiazdą",
"Chorągiewka na wietrze",
"Taniec towarzyski",
"Raz kozie śmierc",
"Jaka mać, taka nać",
"Orzeszki ziemne",
"Czas to pieniądz",
"Król strzelców",
"Włożyć między bajki",
"Rozmowy kontrlolowane",
"Nie wywołuj wilka z lasu",
"Pustka w głowie",
"Głupich nie sieją, sami się rodzą",
"Spisywać na straty",
"Dom na głowie",
"Pańskie oko konia tuczy",
"Oberwanie chmury",
"Zaćmienie słońca",
"Dostać fioła",
"Zamienił stryjek siekierkę na kijek",
"Robota nie zając, nie ucieknie",
"Bóg bez pracy nic nie daje",
"Iść z duchem czasu",
"Jest to cnota nad cnotami trzymać język za zębami",
"Gdzie dwóch się bije, tam trzeci korzysta",
"Szczęśliwy dzień",
"Mieć mocną głowę",
"Cuda wianki",
"Gra zespołowa",
"Strach ma wielkie oczy",
"Kawalerowi wszędzie źle, żonatemu tylko w domu",
"Postawić na swoim",
"Odejść z kwitkiem",
"Wykuć na blache",
"Pokerowa zagrywka",
"Baju, baju będziesz w raju",
"Kość niezgody",
"Czas to pieniądz",
"Olej w głowie",
"Diabeł nie śpi",
"Bez ciekawości nie ma mądrości",
"Lekki jak piórko",
"Chłop się nie przeżegna, dopóki piorunu nie usłyszy",
"Jaka jabłoń, takie jabłka",
"Gdzie kucharek sześć, tam nie ma co jeść",
"Umowa o prace",
"Odwracać kota ogonem",
"Wywinąć orła",
"Potrzeba matką wynalazków",
"Uderz w stół, a nożyce sie odezwą",
"Jak trwoga, to do Boga",
"Kto pod kim dołki kopie, sam w nie wpada",
"Opuścić nos na kwintę",
"Panele słoneczne",
"Idzie luty, podkuj buty",
"Gdzie drwa rąbią, tam wióry lecą",
"Bratnia dusza",
"Głuchy telefon",
"Głupi jak osioł",
"Nie ma dymu bez ognia",
"Ostatnia deska ratunku",
"Latarnia morska",
"Nie czas żałować róż, gdy płoną lasy",
"Ptasie mleczko",
"Ukryte pragnienia",
"Czas leczy rany",
"Od przybytku głowa nie boli",
"Skleroza nie boli, ale nachodzić się trzeba",
"Pałac lodowy",
"Diabelski młyn",
"Słuchaj uchem, a nie brzuchem",
"Cukier w kostkach",
"Czwarty pas, karty w tas",
"Pracowity jak mrówka",
"Walić prosto z mosu",
"Głębokie wykopy",
"Guma balonowa",
"Koń ma cztery nogi i też się potknie",
"Papa Smerf",
"Mieć gołębie serce",
"Dał Bóg dziecko, da na dziecko",
"Poderwać się na równe nogi",
"Płynąć z prądem",
"Im mniej wiesz, tym spokojniej śpisz",
"Remont Kapitalny",
"Co kraj, to obyczaj",
"Kradzione nie tuczy",
"Pamiętaj chemiku młody, wlewaj zawsze kwas do wody",
"Trzymać kogoś pod kloszem",
"Robić coś na własny rachunek",
"Ładnemu we wszystkim ładnie",
"Dla chcącego nic trudnego",
"Gdy się człowiek spieszy, to się diabeł cieszy",
"Dziura zabita dechami",
"Myszy tańcują, gdy kota nie czują",
"Czarny humor",
"Chleb cudzym nożem krajany jest niesmaczny",
"O dwóch takich co ukradli księżyc",
"Pole do popisu",
"Prawda jest córką czasu",
"Gra w piki daje wyniki",
"Trafiła kosa na kamień",
"Tablica korkowa",
"Chłop strzela, a Bóg kule nosi",
"Budować zamki na piasku",
"Podnosić do potęgi",
"Gwiazda filmowa",
"Trzymaj karty przy orderach",
"Siała baba mak",
"Komunikacja miejska",
"Co swój, to nie obcy",
"Nieszczęścia chodzą parami",
"Po trupach do celu",
"Ręka rękę myje",
"Człowiek strzela, a wiatr kule nosi",
"Królewicz z bajki",
"Chlebem i solą ludzie ludzi niewolą",
"Co nagle, to po diable",
"Na dwoje babka wróżyła",
"Nadepnąć komuś na odcisk",
"Ściany mają uszy",
"Pierwsze koty za płoty",
"Nie wszystko złoto, co się świeci",
"Śmiech to zdrowie",
"Płyta główna",
"Lepiej z mądrym zgubić, niż z głupim znaleść",
"Wyścig zbrojeń",
"Żeby kózka nie skakała, toby nóżki nie złamała",
"Upiec dwie pieczenie na jednym ogniu",
"Polak, Węgier – dwa bratanki, i do szabli, i do szklanki",
"Grosz do grosza, a będzie kokosza",
"Lepszy rydz niż nic",
"Beczka bez dna",
"Oszczędnością i pracą ludzie się bogacą",
"Nie graj bawole, czego nie ma na stole",
"Nie od razu Kraków zbudowano",
"Układ scalony",
"Tonący brzytwy się chwyta",
"Siedzieć jak na tureckim kazaniu",
"Jak Kuba Bogu, tak Bóg Kubie",
"Big Ben",
"Kto szuka, ten znajdzie",
"Wolny rynek",
"Nie pamiętał wół, jak cielęciem był",
"Jaka płaca, taka praca",
"Kolorowe kredki",
"W marcu jak w garncu",
"Księżyc w nowiu",
"Tak krawiec kraje, jak mu materii staje",
"Łapać wiatr w żagle",
"Mam na ciebie oko",
"Jak się nie ma, co się lubi, to się lubi, co się ma",
"Bóg dał, Bóg wziął",
"Okno na świat",
"Będzie z niego ksiądz jak z diabła kościelny",
"Układ okresowy pierwiastków",
"Blisko swej jabłoni jabłko pada",
"Bieg przez płotki",
"Róża wiatrów",
"Pleść trzy po trzy",
"Wiadomość dnia",
"Beczka śmiechu",
"Adam cóż by poradził, gdyby Bóg w raju Ewy nie posadził",
"Czego Jaś się nie nauczy, tego Jan nie będzie umiał",
"Co się stało, to się nie odstanie",
"Pies ogroddnika",
"Stół z powyłamywanymi nogami",
"Nauka nie poszła w las",
"Broda mędrcem nie czyni",
"Kto pierwszy, ten lepszy",
"Nie mieć zielonego pojęcia",
"Kropla drąży skałę",
"Kobieca intuicja",
"Jedna owca parszywa całe stado zarazi"

]

from random import randint

def get_words_string(quantity):
    if quantity > len(words):
        raise ValueError()
    else:
        words_list = words[:]
        drawn_words = []
        for i in range(quantity):
            index = randint(0, len(words_list) - 1)
            drawn_words.append(words_list[index])
            words_list.pop(index)
        words_string = ';'.join(drawn_words)
        return words_string
